// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Base.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoregistry "google.golang.org/protobuf/reflect/protoregistry"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	sync "sync"
)

const (
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 0)
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(0 - protoimpl.MinVersion)
)

type Base struct {
	Cmd                    *int32                    `protobuf:"varint,1,req,name=cmd" json:"cmd,omitempty"`
	Code                   *int32                    `protobuf:"varint,2,opt,name=code" json:"code,omitempty"`
	Param                  *int64                    `protobuf:"varint,3,opt,name=param" json:"param,omitempty"`
	LordId                 *int64                    `protobuf:"varint,4,opt,name=lordId" json:"lordId,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                  `json:"-"`
	XXX_InternalExtensions protoimpl.ExtensionFields `json:"-"`
	XXX_unrecognized       protoimpl.UnknownFields   `json:"-"`
	XXX_sizecache          protoimpl.SizeCache       `json:"-"`
}

func (x *Base) Reset() {
	*x = Base{}
}

func (x *Base) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Base) ProtoMessage() {}

func (x *Base) ProtoReflect() protoreflect.Message {
	return file_Base_proto_msgTypes[0].MessageOf(x)
}

func (m *Base) XXX_Methods() *protoiface.Methods {
	return file_Base_proto_msgTypes[0].Methods()
}

// Deprecated: Use Base.ProtoReflect.Type instead.
func (*Base) Descriptor() ([]byte, []int) {
	return file_Base_proto_rawDescGZIP(), []int{0}
}

var extRange_Base = []protoiface.ExtensionRangeV1{
	{Start: 100, End: 536870911},
}

// Deprecated: Use Base.ProtoReflect.Type.ExtensionRanges instead.
func (*Base) ExtensionRangeArray() []protoiface.ExtensionRangeV1 {
	return extRange_Base
}

func (x *Base) GetCmd() int32 {
	if x != nil && x.Cmd != nil {
		return *x.Cmd
	}
	return 0
}

func (x *Base) GetCode() int32 {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return 0
}

func (x *Base) GetParam() int64 {
	if x != nil && x.Param != nil {
		return *x.Param
	}
	return 0
}

func (x *Base) GetLordId() int64 {
	if x != nil && x.LordId != nil {
		return *x.LordId
	}
	return 0
}

var File_Base_proto protoreflect.FileDescriptor

var file_Base_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x42, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4a, 0x0a, 0x04,
	0x42, 0x61, 0x73, 0x65, 0x12, 0x0b, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x05, 0x12, 0x0c, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x12,
	0x0d, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x12, 0x0e,
	0x0a, 0x06, 0x6c, 0x6f, 0x72, 0x64, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x2a, 0x08,
	0x08, 0x64, 0x10, 0x80, 0x80, 0x80, 0x80, 0x02, 0x42, 0x50, 0x0a, 0x1a, 0x63, 0x6f, 0x6d, 0x2e,
	0x68, 0x75, 0x6e, 0x64, 0x72, 0x65, 0x64, 0x63, 0x65, 0x6e, 0x74, 0x2e, 0x67, 0x61, 0x6d, 0x65,
	0x2e, 0x6d, 0x77, 0x2e, 0x70, 0x62, 0x42, 0x06, 0x42, 0x61, 0x73, 0x65, 0x50, 0x62, 0x5a, 0x2a,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x71, 0x69, 0x75, 0x68, 0x6f,
	0x75, 0x64, 0x65, 0x2f, 0x67, 0x6f, 0x2d, 0x77, 0x65, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x76, 0x32, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73,
}

var (
	file_Base_proto_rawDescOnce sync.Once
	file_Base_proto_rawDescData = file_Base_proto_rawDesc
)

func file_Base_proto_rawDescGZIP() []byte {
	file_Base_proto_rawDescOnce.Do(func() {
		file_Base_proto_rawDescData = protoimpl.X.CompressGZIP(file_Base_proto_rawDescData)
	})
	return file_Base_proto_rawDescData
}

var file_Base_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Base_proto_goTypes = []interface{}{
	(*Base)(nil), // 0: Base
}
var file_Base_proto_depIdxs = []int32{}

func init() { file_Base_proto_init() }
func file_Base_proto_init() {
	if File_Base_proto != nil {
		return
	}
	File_Base_proto = protoimpl.FileBuilder{
		RawDescriptor:      file_Base_proto_rawDesc,
		GoTypes:            file_Base_proto_goTypes,
		DependencyIndexes:  file_Base_proto_depIdxs,
		MessageOutputTypes: file_Base_proto_msgTypes,
		FilesRegistry:      protoregistry.GlobalFiles,
		TypesRegistry:      protoregistry.GlobalTypes,
	}.Init()
	file_Base_proto_rawDesc = nil
	file_Base_proto_goTypes = nil
	file_Base_proto_depIdxs = nil
}
